input_number:
  bathroom_set_temperature:
    name: Bathroom target temperature
    max: 25
    min: 13
    step: 0.5
    unit_of_measurement: "°C"

automation:
  - id: climate_bathroom_off
    alias: Climate bathroom off
    description: Turn off the heating when target temp has been reached
    mode: single
    trigger:
      - platform: template
        value_template: >-
          {{ states.sensor.ble_temperature_room_sensor_bathroom.state > states.input_number.bathroom_set_temperature.state }}
    condition: []
    action:
      - service: climate.set_temperature
        target:
          entity_id: climate.thermostaat_bathroom_thermostat
        data:
          temperature: 5
      - service: climate.set_temperature
        target:
          entity_id: climate.bathroom2_thermostat
        data:
          temperature: 5
          

  - id: climate_bathroom_on
    alias: Climate bathroom on
    description: Turn on the heating when actual drops below target temp
    mode: single
    trigger:
      - platform: template
        value_template: >-
          {{ states.sensor.ble_temperature_room_sensor_bathroom.state < states.input_number.bathroom_set_temperature.state }}
    condition: 
      - condition: state
        entity_id: binary_sensor.door_bathroom
        state: 'off'
    action:
      - service: climate.set_temperature
        target:
          entity_id: climate.thermostaat_bathroom_thermostat
        data:
          temperature: 30
      - service: climate.set_temperature
        target:
          entity_id: climate.bathroom2_thermostat
        data:
          temperature: 30

  - id: climate_bathroom_start_schedule_sunday
    alias: Climate bathroom start Sunday
    description: Set target to 20C at defined times
    mode: single
    trigger:
      - platform: time
        at: '13:30:00'
    condition:
      - condition: time
        weekday:
          - sun
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.bathroom_set_temperature
        data:
          value: 20

  - id: climate_bathroom_start_schedule_weekdays
    alias: Climate bathroom start of schedule weekdays
    description: Set target to 20C at defined times
    mode: single
    trigger:
      - platform: time
        at: '06:20:00'
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.bathroom_set_temperature
        data:
          value: 20

  - id: climate_bathroom_stop_schedule_weekdays
    alias: Climate bathroom stop of schedule weekdays
    description: Set target to 20C at defined times
    mode: single
    trigger:
      - platform: time
        at: '07:05:00'
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.bathroom_set_temperature
        data:
          value: 16

  - id: climate_bathroom_stop_schedule_nightly
    alias: Climate bathroom stop nightly
    description: Set target to 20C at defined times
    mode: single
    trigger:
      - platform: time
        at: '22:00:00'
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.wout_set_temperature
        data:
          value: 16

  - id: notify_door_open_bathroom
    alias: Notify_door_bathroom
    description: 'Turn down the heating when door left open'
    trigger:
      - type: opened
        platform: device
        device_id: 7da4adf5d823dce1411176fd44c69ee1
        entity_id: binary_sensor.door_bathroom
        domain: binary_sensor
        for:
          hours: 0
          minutes: 2
          seconds: 30
          milliseconds: 0
    condition:
      - condition: numeric_state
        entity_id: climate.thermostaat_bathroom_thermostat
        attribute: temperature
        above: '16.5'
    action:
      - service: script.speech_notification_service
        data:
          message: Warning, bathroom door is open so I turned off the radiator.
      - service: climate.set_temperature
        target:
          entity_id: climate.thermostaat_bathroom_thermostat
        data:
          temperature: 5
      - service: climate.set_temperature
        target:
          entity_id: climate.bathroom2_thermostat
        data:
          temperature: 5

  - id: climate_bathroom_resume_on_door_closed
    alias: Start bathroom climate when door is closed
    description: 'Start bathroom climate when door is closed'
    trigger:
      - type: not_opened
        platform: device
        device_id: 7da4adf5d823dce1411176fd44c69ee1
        entity_id: binary_sensor.door_bathroom
        domain: binary_sensor
        for:
          hours: 0
          minutes: 1
          seconds: 30
          milliseconds: 0
    condition:
      - condition: numeric_state
        entity_id: climate.thermostaat_bathroom_thermostat
        attribute: temperature
        below: '10'
      - condition: template
        value_template: >-
          {{ states.sensor.ble_temperature_room_sensor_bathroom.state <
          states.input_number.bathroom_set_temperature.state }}
    action:
      - service: script.speech_notification_service
        data:
          message: Bathroom door is closed again. Turning the heating back on.
      - service: climate.set_temperature
        target:
          entity_id: climate.thermostaat_bathroom_thermostat
        data:
          temperature: 30
      - service: climate.set_temperature
        target:
          entity_id: climate.bathroom2_thermostat
        data:
          temperature: 30

  - id: notify_heating_bathroom_on
    alias: Notify_heating_bathroom_on
    description: 'Warn if the room temperature is above 20.5C while outside is below 15C'
    trigger:
      - platform: numeric_state
        entity_id: sensor.ble_temperature_room_sensor_bathroom
        above: '20'
        for:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0
    condition:
      - condition: numeric_state
        entity_id: sensor.openweathermap_temperature
        below: '15'
      - condition: state
        entity_id: climate.thermostaat_bathroom_thermostat
        attribute: hvac_action
        state: heating
    action:
      - service: script.speech_notification_service
        data:
          message: >-
            {{ 'Warning: The bathroom temperature seems high. Please check if the
            heating should be turned down' }}
    mode: single


script:
  thermostat_bathroom_toggle:
    alias: Thermostat bathroom toggle
    sequence:
    - choose:
      - conditions:
        - condition: template
          value_template: '{{ states.input_number.bathroom_set_temperature.state | float(0) > 18.5 }}'
        sequence:
        - service: input_number.set_value
          target:
            entity_id: input_number.bathroom_set_temperature
          data:
            value: 16
      - conditions:
        - condition: template
          value_template: '{{ states.input_number.bathroom_set_temperature.state | float(0) < 16.5 }}'
        sequence:
        - service: input_number.set_value
          target:
            entity_id: input_number.bathroom_set_temperature
          data:
            value: 20
      default: []
    mode: single
    icon: mdi:radiator