  - platform: filter
    name: "Regenwaterput volume"
    entity_id: sensor.watertank_level
    filters:
      - filter: range
        lower_bound: 0
        upper_bound: 4200
      - filter: outlier
        window_size: 15
        radius: 20
      - filter: lowpass
        time_constant: 4
        precision: 0